### ISSUE TITLE
Unable to install it on linux, any ideas?

### ISSUE THREAD

**Issue by eleboss** [lcp29/trimesh-ray-optix#6]
rocessing /home/eleboss/Documents/trimesh-ray-optix
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      In file included from /usr/local/cuda-11.8/bin/../targets/x86_64-linux/include/cuda_runtime.h:115,
                       from <command-line>:
      /usr/local/cuda-11.8/bin/../targets/x86_64-linux/include/crt/common_functions.h:111:10: fatal error: new: No such file or directory
        111 | #include <new>
            |          ^~~~~
      compilation terminated.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/eleboss/Documents/trimesh-ray-optix/setup.py", line 73, in <module>
          compile_and_embed_shaders()
        File "/home/eleboss/Documents/trimesh-ray-optix/setup.py", line 53, in compile_and_embed_shaders
          with open(SHADER_IR_PATH, 'rb') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'triro/backend/embedded/shaders.optixir'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by eleboss** [comment]
`
ome/eleboss/anaconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "/home/eleboss/anaconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/home/eleboss/anaconda3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eleboss/Documents/trimesh-ray-optix/test.py", line 4, in <module>
    from triro.ray.ray_optix import RayMeshIntersector
  File "/home/eleboss/Documents/trimesh-ray-optix/triro/ray/__init__.py", line 18, in <module>
    hops.init_optix()
  File "/home/eleboss/Documents/trimesh-ray-optix/triro/backend/ops.py", line 53, in init_optix
    get_module().initOptix()
    ^^^^^^^^^^^^
  File "/home/eleboss/Documents/trimesh-ray-optix/triro/backend/ops.py", line 37, in get_module
    torch.utils.cpp_extension.load(
  File "/home/eleboss/anaconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/home/eleboss/anaconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/eleboss/anaconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/eleboss/anaconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'triro': [1/4] c++ -MMD -MF binding.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /home/eleboss/anaconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:/include -c /home/eleboss/Documents/trimesh-ray-optix/triro/backend/binding.cpp -o binding.o 
FAILED: binding.o 
c++ -MMD -MF binding.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /home/eleboss/anaconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:/include -c /home/eleboss/Documents/trimesh-ray-optix/triro/backend/binding.cpp -o binding.o 
In file included from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/CUDABuffer.h:19,
                 from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/ray.h:3,
                 from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/binding.cpp:2:
/home/eleboss/Documents/trimesh-ray-optix/triro/backend/optix8.h:21:10: fatal error: optix.h: No such file or directory
   21 | #include <optix.h>
      |          ^~~~~~~~~
compilation terminated.
[2/4] c++ -MMD -MF ray.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /home/eleboss/anaconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:/include -c /home/eleboss/Documents/trimesh-ray-optix/triro/backend/ray.cpp -o ray.o 
FAILED: ray.o 
c++ -MMD -MF ray.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /home/eleboss/anaconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:/include -c /home/eleboss/Documents/trimesh-ray-optix/triro/backend/ray.cpp -o ray.o 
In file included from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/CUDABuffer.h:19,
                 from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/ray.h:3,
                 from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/ray.cpp:8:
/home/eleboss/Documents/trimesh-ray-optix/triro/backend/optix8.h:21:10: fatal error: optix.h: No such file or directory
   21 | #include <optix.h>
      |          ^~~~~~~~~
compilation terminated.
[3/4] c++ -MMD -MF base.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /home/eleboss/anaconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:/include -c /home/eleboss/Documents/trimesh-ray-optix/triro/backend/base.cpp -o base.o 
FAILED: base.o 
c++ -MMD -MF base.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /home/eleboss/anaconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:/include -c /home/eleboss/Documents/trimesh-ray-optix/triro/backend/base.cpp -o base.o 
In file included from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/CUDABuffer.h:19,
                 from /home/eleboss/Documents/trimesh-ray-optix/triro/backend/base.cpp:2:
/home/eleboss/Documents/trimesh-ray-optix/triro/backend/optix8.h:21:10: fatal error: optix.h: No such file or directory
   21 | #include <optix.h>
      |          ^~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.


`

I tried https://github.com/lcp29/trimesh-ray-optix/issues/1
it could be installed but not working at all for the test program

**Comment by lcp29** [comment]
maybe you should add an environment variable OptiX_INSTALL_DIR which points to the OptiX installation?

**Comment by lcp29** [comment]
> maybe you should add an environment variable OptiX_INSTALL_DIR which points to the OptiX installation?

Sorry I didn't see it. Could you try OptiX version 8?

**Comment by lcp29** [comment]
```
[3/4] c++ -MMD -MF base.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /home/eleboss/anaconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:/include -c /home/eleboss/Documents/trimesh-ray-optix/triro/backend/base.cpp -o base.o
```
The including directory looks strange. Can you show how did you set up the OptiX location?

**Comment by eleboss** [comment]
I can manage to install but still unable to run that 
/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eleboss/Documents/trimesh-ray-optix-master/test/test.py", line 4, in <module>
    from triro.ray.ray_optix import RayMeshIntersector
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/ray/__init__.py", line 18, in <module>
    hops.init_optix()
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/backend/ops.py", line 53, in init_optix
    get_module().initOptix()
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/backend/ops.py", line 37, in get_module
    torch.utils.cpp_extension.load(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'triro': [1/4] c++ -MMD -MF base.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/eleboss/anaconda3/envs/hloc/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-8.0.0-linux64-x86_64/include -c /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/backend/base.cpp -o base.o 
[2/4] c++ -MMD -MF ray.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/eleboss/anaconda3/envs/hloc/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-8.0.0-linux64-x86_64/include -c /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/backend/ray.cpp -o ray.o 
[3/4] c++ -MMD -MF binding.o.d -DTORCH_EXTENSION_NAME=triro -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/TH -isystem /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/eleboss/anaconda3/envs/hloc/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -I/home/eleboss/NVIDIA-OptiX-SDK-8.0.0-linux64-x86_64/include -c /home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/backend/binding.cpp -o binding.o 
[4/4] c++ base.o binding.o ray.o -shared -lcuda -L/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o triro.so
FAILED: triro.so 
c++ base.o binding.o ray.o -shared -lcuda -L/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o triro.so
/usr/bin/ld: cannot find -lcuda: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.



what is the installation requirement ?
cuda version
optix version
python and other requirement?

**Comment by eleboss** [comment]
Hi thanks for the response, for the optix I tried 7.7 and 8.0. the setup is basically using the .sh file provided by NVIDIA.
like 
sh /home/eleboss/NVIDIA-OptiX-SDK-8.0.0-linux64-x86_64.sh

**Comment by eleboss** [comment]
then I try to export the environment 
export OptiX_INSTALL_DIR="/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:$OptiX_INSTALL_DIR"

**Comment by eleboss** [comment]
I use cuda-12.1 but installed inside a conda env. Is there anything I need to pay attention to?

**Comment by lcp29** [comment]
> then I try to export the environment export OptiX_INSTALL_DIR="/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64:$OptiX_INSTALL_DIR"

OptiX_INSTALL_DIR is initially empty and a colon is added to the end. 

Try `export OptiX_INSTALL_DIR=/home/eleboss/NVIDIA-OptiX-SDK-7.7.0-linux64-x86_64`

**Comment by eleboss** [comment]
thanks for the response, I use this:

> export OptiX_INSTALL_DIR=/home/eleboss/NVIDIA-OptiX-SDK-8.0.0-linux64-x86_64

But seems the error stills there, missing cuda, that is pretty strange.

**Comment by eleboss** [comment]
```
(hloc) eleboss@eleboss:~/Documents/trimesh-ray-optix-master$ TORCH_CUDA_ARCH_LIST=8.9 python test/test.py
/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.1'
Traceback (most recent call last):
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eleboss/Documents/trimesh-ray-optix-master/test/test.py", line 4, in <module>
    from triro.ray.ray_optix import RayMeshIntersector
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/ray/__init__.py", line 18, in <module>
    hops.init_optix()
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/backend/ops.py", line 53, in init_optix
    get_module().initOptix()
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/triro/backend/ops.py", line 37, in get_module
    torch.utils.cpp_extension.load(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'triro': [1/1] c++ base.o binding.o ray.o -shared -lcuda -L/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda-12.1/lib64 -lcudart -o triro.so
FAILED: triro.so 
c++ base.o binding.o ray.o -shared -lcuda -L/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda-12.1/lib64 -lcudart -o triro.so
/usr/bin/ld: cannot find -lcuda: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by eleboss** [comment]
update: I tried cuda 12.1 and cuda 12.4 some how get this error 
`(hloc) eleboss@eleboss:~/Documents/trimesh-ray-optix$ TORCH_CUDA_ARCH_LIST=8.6 python test/test.py 
/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.4'
Error getting current CUDA context: error code 3
Optix call (optixModuleCreate(optixContext, &moduleCompileOptions, &pipelineCompileOptions, (const char *)shader_code, shader_length, logString, &logStringSize, &optixModule)) failed with code 7051 (line 71)
`

**Comment by lcp29** [comment]
Sorry for the inconvenience. Can you try remove "-lcuda" in line 30, triro/backend/ops.py and reinstall the package?

**Comment by eleboss** [comment]
Hi thanks for the response, I think there is not need to remove the lcuda, that will lose the cuda lib. I manage to reinstalled cuda and my graphic card driver, to 12.4 with 550.0. Now I can install the program and run the test/test.py.

but get the following error:

> loc) (hloc) eleboss@eleboss:~/Documents/trimesh-ray-optix-master$ python test/test.py 
/home/eleboss/anaconda3/envs/hloc/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Optix call (optixModuleCreate(optixContext, &moduleCompileOptions, &pipelineCompileOptions, (const char *)shader_code, shader_length, logString, &logStringSize, &optixModule)) failed with code 7051 (line 71)


do you have any idea how to fix that?
`Optix call (optixModuleCreate(optixContext, &moduleCompileOptions, &pipelineCompileOptions, (const char *)shader_code, shader_length, logString, &logStringSize, &optixModule)) failed with code 7051 (line 71)`

**Comment by lcp29** [comment]
Sorry but I'm a little bit confused. Are you using multiple GPUs on the same machine?
I found a post at https://forums.developer.nvidia.com/t/optixdevicecreatecontext-error-code-7051/231856 and this may help.
By the way, could you provide the full log showing the Python code where the error occurs?

**Comment by eleboss** [comment]
Ok, seems the problem comes from the gcc version, somehow I need to set a correct gcc version for nvcc to ensure it could compile the file and also need to ensure the libcuda.so is correctly placed.
